export const TODO_GET_TODO_LIST_REQ = "TODO_GET_TODO_LIST_REQ";
export const TODO_GET_TODO_LIST_SUCCESS = "TODO_GET_TODO_LIST_SUCCESS";
export const TODO_GET_TODO_LIST_FAIL = "TODO_GET_TODO_LIST_FAIL";
export const TODO_GET_TODO_LIST_CLEAR = "TODO_GET_TODO_LIST_CLEAR";

export const TODO_ADD_TODO_REQ = "TODO_ADD_TODO_REQ";
export const TODO_ADD_TODO_SUCCESS = "TODO_ADD_TODO_SUCCESS";
export const TODO_ADD_TODO_FAIL = "TODO_ADD_TODO_FAIL";
export const TODO_ADD_TODO_CLEAR = "TODO_ADD_TODO_CLEAR";

export const TODO_UPDATE_TODO_REQ = "TODO_UPDATE_TODO_REQ";
export const TODO_UPDATE_TODO_SUCCESS = "TODO_UPDATE_TODO_SUCCESS";
export const TODO_UPDATE_TODO_FAIL = "TODO_UPDATE_TODO_FAIL";
export const TODO_UPDATE_TODO_CLEAR = "TODO_UPDATE_TODO_CLEAR";

export const TODO_DELETE_TODO_REQ = "TODO_DELETE_TODO_REQ";
export const TODO_DELETE_TODO_SUCCESS = "TODO_DELETE_TODO_SUCCESS";
export const TODO_DELETE_TODO_FAIL = "TODO_DELETE_TODO_FAIL";
export const TODO_DELETE_TODO_CLEAR = "TODO_DELETE_TODO_CLEAR";

export const TODO_AUTH_ADD_TODO_REQ = "TODO_AUTH_ADD_TODO_REQ";
export const TODO_AUTH_ADD_TODO_SUCCESS = "TODO_AUTH_ADD_TODO_SUCCESS";
export const TODO_AUTH_ADD_TODO_FAIL = "TODO_AUTH_ADD_TODO_FAIL";
export const TODO_AUTH_ADD_TODO_CLEAR = "TODO_AUTH_ADD_TODO_CLEAR";

export const TODO_AUTH_UPDATE_TODO_REQ = "TODO_AUTH_UPDATE_TODO_REQ";
export const TODO_AUTH_UPDATE_TODO_SUCCESS = "TODO_AUTH_UPDATE_TODO_SUCCESS";
export const TODO_AUTH_UPDATE_TODO_FAIL = "TODO_AUTH_UPDATE_TODO_FAIL";
export const TODO_AUTH_UPDATE_TODO_CLEAR = "TODO_AUTH_UPDATE_TODO_CLEAR";

export const TODO_AUTH_DELETE_TODO_REQ = "TODO_AUTH_DELETE_TODO_REQ";
export const TODO_AUTH_DELETE_TODO_SUCCESS = "TODO_AUTH_DELETE_TODO_SUCCESS";
export const TODO_AUTH_DELETE_TODO_FAIL = "TODO_AUTH_DELETE_TODO_FAIL";
export const TODO_AUTH_DELETE_TODO_CLEAR = "TODO_AUTH_DELETE_TODO_CLEAR";
