export const INCREMENT_REQ = "INCREMENT_REQ";
export const INCREMENT_SUCCESS = "INCREMENT_SUCCESS";
export const INCREMENT_FAIL = "INCREMENT_FAIL";

export const DECREMENT_REQ = "DECREMENT_REQ";
export const DECREMENT_SUCCESS = "DECREMENT_SUCCESS";
export const DECREMENT_FAIL = "DECREMENT_FAIL";

export const API_REQ = "API_REQ";
export const API_SUCCESS = "API_SUCCESS";
export const API_FAIL = "API_FAIL";
