export const AUTH_LOGIN_REQ = "AUTH_LOGIN_REQ";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_LOGIN_CLEAR = "AUTH_LOGIN_CLEAR";
